[package]
name = "cargo-override"
version = "0.0.6"
edition = "2021"
rust-version = "1.83"
license = "Apache-2.0 OR MIT"
description = """
Quickly override dependencies using the `[patch]` section of `Cargo.toml`s.
"""
repository = "https://github.com/eopb/cargo-override"

[features]
# Used to introduce TDD style tests, that are known to fail now, without breaking CI.
#
# These tests are marked with `#[cfg_attr(not(feature = "failing_tests"), should_panic)]`.
# Once the bugs are fixed, and these tests start passing, those attributes need to be
# removed.
#
# You can run these special tests now with `cargo test --features failing_tests`
failing_tests = []

[dependencies]
anyhow = "1.0.98"
camino = "1.1.9"
cargo = "0.88.0"
cargo_metadata = "0.20"
cargo-util-schemas = "0.8.1"
clap = { version = "4.5.39", features = ["derive"] }
fs-err = "3.1.0"
home = "0.5.11"
pathdiff = "0.2.3"
semver = "1.0.26"
serde = { version = "1.0.219", features = ["derive"] }
toml_edit = "0.22.24"
url = "2.5.4"
winnow = "0.7.10"
clap-cargo = "0.15.2"

[dev-dependencies]
assert_cmd = "2.0.17"
fake = "4.3.0"
googletest = "0.14.1"
hex = "0.4.3"
insta = { version = "1.41.1", features = ["filters", "toml"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
strip-ansi-escapes = "0.2.1"
tempfile = "3.20.0"
test-case = "3.3.1"

# Faster snapshotting https://insta.rs/docs/quickstart/#optional-faster-runs
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
