name: update-flake-lock

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            github_actions
