name: Nix

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions: read-all

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}

    name: flake check
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check -L --show-trace
  fmt:
    runs-on: ubuntu-latest

    name: nix fmt
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix run nixpkgs#nixfmt-rfc-style -- --check flake.nix
